/* eslint-disable max-len */

export const deals = [
  {
    dealId: '1',
    mainTitle: 'Castille et Carillon',
    availableShares: '187',
    shareholder: 'Feldman Equities',
    targetedInvestorIrr: '16.7%',
    targetedEquityMultiple: '1.8x',
    targetedAvarageCashYield: '10.5%',
    distributionCommencement: '$25,000',
    distributionPeriod: '8 years',
    dealInfo: {
      dealTitle: 'Ariston Navigation',
      description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ',
      transactions: [
        {
          advertiser: 'user',
          available: '85.75',
          price: '1.04 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user2',
          available: '90.05',
          price: '1.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user3',
          available: '64.15',
          price: '2.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user4',
          available: '104.01',
          price: '4.15 GBP',
          acceptedCurrency: 'GBP',
        },
      ],
    },
  },
  {
    dealId: '2',
    mainTitle: 'Castille et Carillon',
    availableShares: '187',
    shareholder: 'Feldman Equities',
    targetedInvestorIrr: '16.7%',
    targetedEquityMultiple: '1.8x',
    targetedAvarageCashYield: '10.5%',
    distributionCommencement: '$25,000',
    distributionPeriod: '8 years',
    dealInfo: {
      dealTitle: 'Ariston Navigation',
      description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ',
      transactions: [
        {
          advertiser: 'user',
          available: '85.75',
          price: '1.04 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user2',
          available: '90.05',
          price: '1.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user3',
          available: '64.15',
          price: '2.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user4',
          available: '104.01',
          price: '4.15 GBP',
          acceptedCurrency: 'GBP',
        },
      ],
    },
  },
  {
    dealId: '3',
    mainTitle: 'Castille et Carillon',
    availableShares: '187',
    shareholder: 'Feldman Equities',
    targetedInvestorIrr: '16.7%',
    targetedEquityMultiple: '1.8x',
    targetedAvarageCashYield: '10.5%',
    distributionCommencement: '$25,000',
    distributionPeriod: '8 years',
    dealInfo: {
      dealTitle: 'Ariston Navigation',
      description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ',
      transactions: [
        {
          advertiser: 'user',
          available: '85.75',
          price: '1.04 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user2',
          available: '90.05',
          price: '1.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user3',
          available: '64.15',
          price: '2.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user4',
          available: '104.01',
          price: '4.15 GBP',
          acceptedCurrency: 'GBP',
        },
      ],
    },
  },
  {
    dealId: '4',
    mainTitle: 'Castille et Carillon',
    availableShares: '187',
    shareholder: 'Feldman Equities',
    targetedInvestorIrr: '16.7%',
    targetedEquityMultiple: '1.8x',
    targetedAvarageCashYield: '10.5%',
    distributionCommencement: '$25,000',
    distributionPeriod: '8 years',
    dealInfo: {
      dealTitle: 'Ariston Navigation',
      description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ',
      transactions: [
        {
          advertiser: 'user',
          available: '85.75',
          price: '1.04 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user2',
          available: '90.05',
          price: '1.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user3',
          available: '64.15',
          price: '2.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user4',
          available: '104.01',
          price: '4.15 GBP',
          acceptedCurrency: 'GBP',
        },
      ],
    },
  },
  {
    dealId: '5',
    mainTitle: 'Castille et Carillon',
    availableShares: '187',
    shareholder: 'Feldman Equities',
    targetedInvestorIrr: '16.7%',
    targetedEquityMultiple: '1.8x',
    targetedAvarageCashYield: '10.5%',
    distributionCommencement: '$25,000',
    distributionPeriod: '8 years',
    dealInfo: {
      dealTitle: 'Ariston Navigation',
      description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ',
      transactions: [
        {
          advertiser: 'user',
          available: '85.75',
          price: '1.04 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user2',
          available: '90.05',
          price: '1.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user3',
          available: '64.15',
          price: '2.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user4',
          available: '104.01',
          price: '4.15 GBP',
          acceptedCurrency: 'GBP',
        },
      ],
    },
  },
  {
    dealId: '6',
    mainTitle: 'Castille et Carillon',
    availableShares: '187',
    shareholder: 'Feldman Equities',
    targetedInvestorIrr: '16.7%',
    targetedEquityMultiple: '1.8x',
    targetedAvarageCashYield: '10.5%',
    distributionCommencement: '$25,000',
    distributionPeriod: '8 years',
    dealInfo: {
      dealTitle: 'Ariston Navigation',
      description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ',
      transactions: [
        {
          advertiser: 'user',
          available: '85.75',
          price: '1.04 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user2',
          available: '90.05',
          price: '1.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user3',
          available: '64.15',
          price: '2.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user4',
          available: '104.01',
          price: '4.15 GBP',
          acceptedCurrency: 'GBP',
        },
      ],
    },
  },
  {
    dealId: '7',
    mainTitle: 'Castille et Carillon',
    availableShares: '187',
    shareholder: 'Feldman Equities',
    targetedInvestorIrr: '16.7%',
    targetedEquityMultiple: '1.8x',
    targetedAvarageCashYield: '10.5%',
    distributionCommencement: '$25,000',
    distributionPeriod: '8 years',
    dealInfo: {
      dealTitle: 'Ariston Navigation',
      description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ',
      transactions: [
        {
          advertiser: 'user',
          available: '85.75',
          price: '1.04 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user2',
          available: '90.05',
          price: '1.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user3',
          available: '64.15',
          price: '2.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user4',
          available: '104.01',
          price: '4.15 GBP',
          acceptedCurrency: 'GBP',
        },
      ],
    },
  },
  {
    dealId: '8',
    mainTitle: 'Castille et Carillon',
    availableShares: '187',
    shareholder: 'Feldman Equities',
    targetedInvestorIrr: '16.7%',
    targetedEquityMultiple: '1.8x',
    targetedAvarageCashYield: '10.5%',
    distributionCommencement: '$25,000',
    distributionPeriod: '8 years',
    dealInfo: {
      dealTitle: 'Ariston Navigation',
      description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ',
      transactions: [
        {
          advertiser: 'user',
          available: '85.75',
          price: '1.04 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user2',
          available: '90.05',
          price: '1.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user3',
          available: '64.15',
          price: '2.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user4',
          available: '104.01',
          price: '4.15 GBP',
          acceptedCurrency: 'GBP',
        },
      ],
    },
  },
  {
    dealId: '9',
    mainTitle: 'Castille et Carillon',
    availableShares: '187',
    shareholder: 'Feldman Equities',
    targetedInvestorIrr: '16.7%',
    targetedEquityMultiple: '1.8x',
    targetedAvarageCashYield: '10.5%',
    distributionCommencement: '$25,000',
    distributionPeriod: '8 years',
    dealInfo: {
      dealTitle: 'Ariston Navigation',
      description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ',
      transactions: [
        {
          advertiser: 'user',
          available: '85.75',
          price: '1.04 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user2',
          available: '90.05',
          price: '1.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user3',
          available: '64.15',
          price: '2.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user4',
          available: '104.01',
          price: '4.15 GBP',
          acceptedCurrency: 'GBP',
        },
      ],
    },
  },
  {
    dealId: '10',
    mainTitle: 'Castille et Carillon',
    availableShares: '187',
    shareholder: 'Feldman Equities',
    targetedInvestorIrr: '16.7%',
    targetedEquityMultiple: '1.8x',
    targetedAvarageCashYield: '10.5%',
    distributionCommencement: '$25,000',
    distributionPeriod: '8 years',
    dealInfo: {
      dealTitle: 'Ariston Navigation',
      description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ',
      transactions: [
        {
          advertiser: 'user',
          available: '85.75',
          price: '1.04 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user2',
          available: '90.05',
          price: '1.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user3',
          available: '64.15',
          price: '2.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user4',
          available: '104.01',
          price: '4.15 GBP',
          acceptedCurrency: 'GBP',
        },
      ],
    },
  },
  {
    dealId: '11',
    mainTitle: 'Castille et Carillon',
    availableShares: '187',
    shareholder: 'Feldman Equities',
    targetedInvestorIrr: '16.7%',
    targetedEquityMultiple: '1.8x',
    targetedAvarageCashYield: '10.5%',
    distributionCommencement: '$25,000',
    distributionPeriod: '8 years',
    dealInfo: {
      dealTitle: 'Ariston Navigation',
      description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ',
      transactions: [
        {
          advertiser: 'user',
          available: '85.75',
          price: '1.04 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user2',
          available: '90.05',
          price: '1.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user3',
          available: '64.15',
          price: '2.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user4',
          available: '104.01',
          price: '4.15 GBP',
          acceptedCurrency: 'GBP',
        },
      ],
    },
  },
  {
    dealId: '12',
    mainTitle: 'Castille et Carillon',
    availableShares: '187',
    shareholder: 'Feldman Equities',
    targetedInvestorIrr: '16.7%',
    targetedEquityMultiple: '1.8x',
    targetedAvarageCashYield: '10.5%',
    distributionCommencement: '$25,000',
    distributionPeriod: '8 years',
    dealInfo: {
      dealTitle: 'Ariston Navigation',
      description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ',
      transactions: [
        {
          advertiser: 'user',
          available: '85.75',
          price: '1.04 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user2',
          available: '90.05',
          price: '1.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user3',
          available: '64.15',
          price: '2.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user4',
          available: '104.01',
          price: '4.15 GBP',
          acceptedCurrency: 'GBP',
        },
      ],
    },
  },
  {
    dealId: '13',
    mainTitle: 'Castille et Carillon',
    availableShares: '187',
    shareholder: 'Feldman Equities',
    targetedInvestorIrr: '16.7%',
    targetedEquityMultiple: '1.8x',
    targetedAvarageCashYield: '10.5%',
    distributionCommencement: '$25,000',
    distributionPeriod: '8 years',
    dealInfo: {
      dealTitle: 'Ariston Navigation',
      description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ',
      transactions: [
        {
          advertiser: 'user',
          available: '85.75',
          price: '1.04 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user2',
          available: '90.05',
          price: '1.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user3',
          available: '64.15',
          price: '2.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user4',
          available: '104.01',
          price: '4.15 GBP',
          acceptedCurrency: 'GBP',
        },
      ],
    },
  },
  {
    dealId: '14',
    mainTitle: 'Castille et Carillon',
    availableShares: '187',
    shareholder: 'Feldman Equities',
    targetedInvestorIrr: '16.7%',
    targetedEquityMultiple: '1.8x',
    targetedAvarageCashYield: '10.5%',
    distributionCommencement: '$25,000',
    distributionPeriod: '8 years',
    dealInfo: {
      dealTitle: 'Ariston Navigation',
      description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ',
      transactions: [
        {
          advertiser: 'user',
          available: '85.75',
          price: '1.04 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user2',
          available: '90.05',
          price: '1.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user3',
          available: '64.15',
          price: '2.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user4',
          available: '104.01',
          price: '4.15 GBP',
          acceptedCurrency: 'GBP',
        },
      ],
    },
  },
  {
    dealId: '15',
    mainTitle: 'Castille et Carillon',
    availableShares: '187',
    shareholder: 'Feldman Equities',
    targetedInvestorIrr: '16.7%',
    targetedEquityMultiple: '1.8x',
    targetedAvarageCashYield: '10.5%',
    distributionCommencement: '$25,000',
    distributionPeriod: '8 years',
    dealInfo: {
      dealTitle: 'Ariston Navigation',
      description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ',
      transactions: [
        {
          advertiser: 'user',
          available: '85.75',
          price: '1.04 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user2',
          available: '90.05',
          price: '1.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user3',
          available: '64.15',
          price: '2.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user4',
          available: '104.01',
          price: '4.15 GBP',
          acceptedCurrency: 'GBP',
        },
      ],
    },
  },
  {
    dealId: '16',
    mainTitle: 'Castille et Carillon',
    availableShares: '187',
    shareholder: 'Feldman Equities',
    targetedInvestorIrr: '16.7%',
    targetedEquityMultiple: '1.8x',
    targetedAvarageCashYield: '10.5%',
    distributionCommencement: '$25,000',
    distributionPeriod: '8 years',
    dealInfo: {
      dealTitle: 'Ariston Navigation',
      description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ',
      transactions: [
        {
          advertiser: 'user',
          available: '85.75',
          price: '1.04 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user2',
          available: '90.05',
          price: '1.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user3',
          available: '64.15',
          price: '2.15 GBP',
          acceptedCurrency: 'GBP',
        },
        {
          advertiser: 'user4',
          available: '104.01',
          price: '4.15 GBP',
          acceptedCurrency: 'GBP',
        },
      ],
    },
  },
];
